### ISSUE TITLE
Compatibility with flake8 6.0

### ISSUE THREAD

**Issue by philpep** [MarcinBinkowski/flake8_unused_fixtures#4]
Hi due to dependencies flake8-unused-fixtures requires flake8<6.0.0:

`flake8-unused-fixtures 0.3.1 has requirement flake8<6.0.0,>=5.0.4, but you have flake8 6.1.0.`

Which is causing issues when installing along with some other flake8 plugin requiring >=6.0.

Since the plugin actually works with flake8 6.0 I suggest to drop the `<6.0.0` (dunno how to handle this with poetry through).

Thanks!

**Comment by MarcinBinkowski** [comment]
Dropped strict dependency version
